name: Build and run

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Show build environment
        run: |
            echo -n "CC: "; cc --version

      - name: Build mirror
        run: |
            make mirror

      - name: Run mirror
        run: |
            ./mirror
